server:
  port: 9091
feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 50000000
        readTimeout: 5000000
        loggerLevel: FULL
client:
  dome:
    baseUrl: http://localhost:9090/dome